title: "George French"
author: "George French"
description: "Mostly aviation musings."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "about.md", icon: address-card}

external:                  # see http://fontawesome.com/icons
  - {title: Instagram, icon: instagram, url: "https://instagram.com/gfrnch"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
